image: Visual Studio 2017
clone_depth: 5

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - cd ..
  - mkdir build
  - cd build
  - cmake -A x64
          -DCMAKE_C_FLAGS="/wd4101 /wd4996"
          -DBUILD_TESTING=OFF
          ..\libxc

build_script:
  - cmake --build .

test_script:
  - ctest --build-config Debug