image: Visual Studio 2017
clone_depth: 5

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - mkdir libxc_build && cd libxc_build
  - cmake -A x64
          -DENABLE_XHOST=OFF
          -DCMAKE_C_FLAGS="/wd4101 /wd4996"
          ..

build_script:
  - cmake --build .

test_script:
  - ctest --build-config Debug
          -E "mgga_x_b00-*" # Broken on Windows
